/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swiftbase;

/**
 *
 * @author Raichuu
 */
public class SwiftBase_Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SwiftBase_Login.class.getName());

    /**
     * Creates new form SwiftBase
     */
    public SwiftBase_Login() {
        initComponents();
        Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
Register.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        new registerFrame().setVisible(true);
        dispose();
    }
});
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_Form = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        password = new javax.swing.JLabel();
        email_l1 = new javax.swing.JLabel();
        login_btn = new javax.swing.JButton();
        email_field = new javax.swing.JTextField();
        remember_me = new javax.swing.JCheckBox();
        forgot_password = new javax.swing.JLabel();
        dont_have_account = new javax.swing.JLabel();
        Register = new javax.swing.JLabel();
        BGIM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_Form.setBackground(new java.awt.Color(21, 26, 43));
        Login_Form.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        login.setBackground(new java.awt.Color(204, 204, 204));
        login.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");

        password_field.setBackground(new java.awt.Color(38, 26, 87));
        password_field.setForeground(new java.awt.Color(255, 255, 255));
        password_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");

        email_l1.setBackground(new java.awt.Color(255, 255, 255));
        email_l1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        email_l1.setForeground(new java.awt.Color(255, 255, 255));
        email_l1.setText("Email");

        login_btn.setBackground(new java.awt.Color(38, 38, 144));
        login_btn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        login_btn.setForeground(new java.awt.Color(255, 255, 255));
        login_btn.setText("-Login-");
        login_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        login_btn.addActionListener(this::login_btnActionPerformed);

        email_field.setBackground(new java.awt.Color(38, 26, 87));
        email_field.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        email_field.setForeground(new java.awt.Color(255, 255, 255));
        email_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        remember_me.setForeground(new java.awt.Color(255, 255, 255));
        remember_me.setText("Remember me");
        remember_me.addActionListener(this::remember_meActionPerformed);

        forgot_password.setBackground(new java.awt.Color(153, 153, 153));
        forgot_password.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        forgot_password.setForeground(new java.awt.Color(255, 255, 255));
        forgot_password.setText("forgot password?");

        dont_have_account.setBackground(new java.awt.Color(255, 255, 255));
        dont_have_account.setForeground(new java.awt.Color(255, 255, 255));
        dont_have_account.setText("Don't have an account?");

        Register.setBackground(new java.awt.Color(204, 0, 51));
        Register.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setText(" Register");

        javax.swing.GroupLayout Login_FormLayout = new javax.swing.GroupLayout(Login_Form);
        Login_Form.setLayout(Login_FormLayout);
        Login_FormLayout.setHorizontalGroup(
            Login_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_FormLayout.createSequentialGroup()
                .addGroup(Login_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Login_FormLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(Login_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Login_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(Login_FormLayout.createSequentialGroup()
                                    .addComponent(remember_me)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                    .addComponent(forgot_password))
                                .addComponent(email_l1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(password_field, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(email_field, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(Login_FormLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(dont_have_account, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Login_FormLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Login_FormLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(login)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        Login_FormLayout.setVerticalGroup(
            Login_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_FormLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(email_l1)
                .addGap(9, 9, 9)
                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Login_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remember_me)
                    .addComponent(forgot_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Login_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dont_have_account)
                    .addComponent(Register))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(Login_Form, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 300, 360));

        BGIM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg1(updated).png"))); // NOI18N
        getContentPane().add(BGIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
         String mail = email_field.getText().trim();
    String pass = new String(password_field.getPassword()).trim();

    if (mail.isEmpty() || pass.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter email and password.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    try (java.sql.Connection conn = DBConnection.getConnection()) {
        String sql = "SELECT * FROM users WHERE email = ? AND password = ?";
        java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, mail);
        stmt.setString(2, pass);
        java.sql.ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            String loggedInUser = rs.getString("username");
            javax.swing.JOptionPane.showMessageDialog(this, "Welcome, " + loggedInUser + "!", "Login Successful", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Open Dashboard
            javax.swing.JFrame dashFrame = new javax.swing.JFrame("SwiftBase - Dashboard");
            dashboardFrame dashboard = new dashboardFrame();
            dashFrame.setContentPane(dashboard);
            dashFrame.setSize(720, 480);
            dashFrame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            dashFrame.setLocationRelativeTo(null);
            dashFrame.setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid email or password.", "Login Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_login_btnActionPerformed

    private void remember_meActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remember_meActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remember_meActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SwiftBase_Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGIM;
    private javax.swing.JPanel Login_Form;
    private javax.swing.JLabel Register;
    private javax.swing.JLabel dont_have_account;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel email_l1;
    private javax.swing.JLabel forgot_password;
    private javax.swing.JLabel login;
    private javax.swing.JButton login_btn;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JCheckBox remember_me;
    // End of variables declaration//GEN-END:variables
}
